//parameters
pz(1) = 6.60    //k_fqdoR»     constant of formation of the qdoR protein(min-1) (Ross & Orlowski, 1982)
pz(2)= 11.04    //k_fgfp»      constant of formation of GFProtein(min-1) (Berset et al., 2017)
pz(3) = 3D-5    //K_dR»     First order rate constant for the degradation of repressor (min-1) 
pz(4) = 5D-4    //K_dgfp»        First order rate constant for the degradation of GFProtein (min-1) (Berset et al., 2017)
pz(5) = 2.5D-12    //[Q]»        concentration of total quercetin in the cell (mol L-1)(Said et al., 2016)
pz(6) = 166D-11    //[r]_T»      Total concentration of Repressor gene in the cell (mol L-1) (Conversion in mol/L of 1 copy/cell  )(Berset et al., 2017)
pz(7)= 166D-11    //[b]_T»     Total concentration of Biomarker gene in the cell (mol L-1)(Conversion in mol/L of 1 copy/cell  )(Berset et al., 2017)
pz(8) = 1D-4    //K_dQ»      Dissociation constant for the “Q~R” complex (M)(Hirooka & Fujita, 2011)
pz(9)= 1D-3        //K_dQ2»      Dissociation constant for the “Q²~R” complex (M)(choosen)
pz(10) = 9D-9    //K_dR»      Dissociation constant for the “Promoter~R” complex (M)(Hirooka & Fujita, 2011)
pz(11)= 1D-9    //K_dB»     Dissociation constant for the "Biomarker~R" complex (M)(Hirooka & Fujita, 2011)
pz(12) = 0.0033    //r»       Constant for volume increase.(choosen)
pz(13) =6.5D-15     // k»     Carrying capacity. (L) (Choosen)
pz(14) = 7.20D-2       //GFPm»       Maturation constant of gfp(min-1) (Berset et al., 2017)
[VrSTR]= [0.1; 0.15; 0.16; 0.24; 0.33; 0.45]    //vr = velocity of production of repressor (mol repressor L-1 min-1) (anderson promoter)
